// <auto-generated />
using System;
using BANKING_SYSTEM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BANKING_SYSTEM.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BANKING_SYSTEME.Models.Client", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code_postal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BANKING_SYSTEME.Models.Compte", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("AutorisationDecouvert")
                        .HasColumnType("bit");

                    b.Property<int>("Clientid")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOuverture")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontantDecouvert")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumAcc")
                        .HasColumnType("int");

                    b.Property<decimal>("Solde")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TypeCompte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Clientid");

                    b.ToTable("Comptes");

                    b.HasDiscriminator().HasValue("Compte");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BANKING_SYSTEME.Models.Livret", b =>
                {
                    b.HasBaseType("BANKING_SYSTEME.Models.Compte");

                    b.Property<double>("TauxDeRenumeration")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Livret");
                });

            modelBuilder.Entity("BANKING_SYSTEME.Models.PEL", b =>
                {
                    b.HasBaseType("BANKING_SYSTEME.Models.Compte");

                    b.Property<double>("TauxDeRenumeration")
                        .HasColumnType("float");

                    b.ToTable("Comptes", t =>
                        {
                            t.Property("TauxDeRenumeration")
                                .HasColumnName("PEL_TauxDeRenumeration");
                        });

                    b.HasDiscriminator().HasValue("PEL");
                });

            modelBuilder.Entity("BANKING_SYSTEME.Models.Compte", b =>
                {
                    b.HasOne("BANKING_SYSTEME.Models.Client", "Client")
                        .WithMany("Comptes")
                        .HasForeignKey("Clientid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BANKING_SYSTEME.Models.Client", b =>
                {
                    b.Navigation("Comptes");
                });
#pragma warning restore 612, 618
        }
    }
}
